- name: Uninstall loki-server
  pkg:
    name: loki-server
    state: absent
  failed_when: false

- name: Assert loki is removed
  assert:
    command:
      cmd: command -v loki
      exit_code: 1

- name: Display confirmation
  log: "loki-server uninstalled"
