- name: Uninstall alacritty
  pkg:
    name: alacritty
    state: absent
  failed_when: false

- name: Display confirmation
  log: "alacritty uninstalled"
- name: Verify uninstallation with assert
  assert:
    command:
      cmd: command -v alacritty
      exit_code: 1
