- name: Uninstall milvus
  pkg:
    name: milvus
    state: absent
  failed_when: false

- name: Display confirmation
  log: "milvus uninstalled"
- name: Assert tool is removed
  assert:
    command:
      cmd: command -v milvus
      exit_code: 1
