package executor

import (
	"strings"
	"testing"

	"github.com/alehatsman/mooncake/internal/config"
)

// TestSynthesizeStepName_PerActionFormatters drives every per-action
// arm. Cases mirror the reference table in dx proposal-01 so the
// rendered shape stays in lockstep with the spec.
func TestSynthesizeStepName_PerActionFormatters(t *testing.T) {
	tmpl := "/etc/foo.conf"
	importPath := "tasks/x.yml"
	vars := map[string]interface{}{"a": 1, "b": 2, "c": 3}

	cases := []struct {
		name string
		step config.Step
		want string
	}{
		{
			name: "shell short cmd",
			step: config.Step{Shell: &config.ShellAction{Cmd: "echo hi"}},
			want: "shell: echo hi",
		},
		{
			name: "shell collapses whitespace",
			step: config.Step{Shell: &config.ShellAction{Cmd: "echo\n  hi\tthere"}},
			want: "shell: echo hi there",
		},
		{
			name: "file.write path",
			step: config.Step{FileWrite: &config.File{Path: "/tmp/x.txt"}},
			want: "file.write /tmp/x.txt",
		},
		{
			name: "file.download dest",
			step: config.Step{FileDownload: &config.Download{URL: "https://x/y", Dest: "/opt/foo"}},
			want: "file.download → /opt/foo",
		},
		{
			name: "file.copy dest",
			step: config.Step{FileCopy: &config.Copy{Src: "a", Dest: "/etc/b"}},
			want: "file.copy /etc/b",
		},
		{
			name: "file.template dest",
			step: config.Step{FileTemplate: &config.Template{Src: "s.tpl", Dest: tmpl}},
			want: "file.template /etc/foo.conf",
		},
		{
			name: "pkg single name",
			step: config.Step{Pkg: &config.Package{Name: "jq"}},
			want: "pkg jq",
		},
		{
			name: "pkg multi names",
			step: config.Step{Pkg: &config.Package{Names: []string{"jq", "yq", "curl"}}},
			want: "pkg jq (+2)",
		},
		{
			name: "log msg",
			step: config.Step{Log: &config.PrintAction{Msg: "hello"}},
			want: "log: hello",
		},
		{
			name: "http.request default GET",
			step: config.Step{HTTPRequest: &config.HTTPRequest{URL: "http://x/api"}},
			want: "http.request: GET http://x/api",
		},
		{
			name: "http.request explicit POST",
			step: config.Step{HTTPRequest: &config.HTTPRequest{Method: "POST", URL: "http://x/api"}},
			want: "http.request: POST http://x/api",
		},
		{
			name: "import path",
			step: config.Step{Import: &importPath},
			want: "import: tasks/x.yml",
		},
		{
			name: "vars count",
			step: config.Step{Vars: &vars},
			want: "vars: (3 keys)",
		},
		{
			name: "os.user name",
			step: config.Step{OsUser: &config.OsUser{Name: "deploy"}},
			want: "os.user deploy",
		},
		{
			name: "os.group name",
			step: config.Step{OsGroup: &config.OsGroup{Name: "docker"}},
			want: "os.group docker",
		},
		{
			name: "os.service name",
			step: config.Step{OsService: &config.ServiceAction{Name: "nginx"}},
			want: "os.service nginx",
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := synthesizeStepName(c.step)
			if got != c.want {
				t.Errorf("synthesizeStepName = %q, want %q", got, c.want)
			}
		})
	}
}

// TestSynthesizeStepName_Transaction renders a compound step
// summary. Uses the (N children) convention from the proposal.
func TestSynthesizeStepName_Transaction(t *testing.T) {
	step := config.Step{
		Transaction: []config.Step{{}, {}, {}},
	}
	got := synthesizeStepName(step)
	want := "transaction: (3 children)"
	if got != want {
		t.Errorf("synthesizeStepName = %q, want %q", got, want)
	}
}

// TestSynthesizeStepName_Try_WithCatchAndFinally covers all three
// flags so the label tells operators what shape this try-block has
// without re-opening the YAML.
func TestSynthesizeStepName_Try_WithCatchAndFinally(t *testing.T) {
	cases := []struct {
		name string
		step config.Step
		want string
	}{
		{
			name: "try only",
			step: config.Step{Try: []config.Step{{}, {}}},
			want: "try: (2 children)",
		},
		{
			name: "try with catch",
			step: config.Step{Try: []config.Step{{}, {}}, Catch: []config.Step{{}}},
			want: "try: (2 children, +catch)",
		},
		{
			name: "try with catch + finally",
			step: config.Step{Try: []config.Step{{}}, Catch: []config.Step{{}}, Finally: []config.Step{{}}},
			want: "try: (1 children, +catch, +finally)",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := synthesizeStepName(c.step)
			if got != c.want {
				t.Errorf("synthesizeStepName = %q, want %q", got, c.want)
			}
		})
	}
}

// TestSynthesizeStepName_TruncatesLongBody catches the operator's
// "5000-step playbook generated by for $(seq 1 5000)" case from the
// proposal's receipts. Long shell commands collapse to a single
// line and truncate with `…`.
func TestSynthesizeStepName_TruncatesLongBody(t *testing.T) {
	long := strings.Repeat("a", 200)
	step := config.Step{Shell: &config.ShellAction{Cmd: long}}
	got := synthesizeStepName(step)
	if len([]rune(got)) > labelMaxLen {
		t.Errorf("synthesizeStepName length = %d, must be <= %d (got %q)", len([]rune(got)), labelMaxLen, got)
	}
	if !strings.HasSuffix(got, labelEllip) {
		t.Errorf("truncated label must end with %q; got %q", labelEllip, got)
	}
}

// TestSynthesizeStepName_EmptyStepReturnsEmpty pins backwards
// compatibility for `coverage_boost_test.go:TestGetStepDisplayName_
// NoName` — a fully empty step must NOT synthesize a misleading
// "unknown" label. The caller falls back to a blank step row.
func TestSynthesizeStepName_EmptyStepReturnsEmpty(t *testing.T) {
	got := synthesizeStepName(config.Step{})
	if got != "" {
		t.Errorf("empty step must not synthesize; got %q", got)
	}
}

// TestSynthesizeStepName_LoopStepReturnsEmpty — bare for_each /
// with_files wrappers aren't useful to label here. The loop
// children produce their own labels and the existing with_items
// path in getStepDisplayName already covers iteration display.
func TestSynthesizeStepName_LoopStepReturnsEmpty(t *testing.T) {
	step := config.Step{ForEach: &config.ForEachField{}}
	got := synthesizeStepName(step)
	if got != "" {
		t.Errorf("loop step must not synthesize; got %q", got)
	}
}

// TestSynthesizeStepName_NamedStepWinsViaGetStepDisplayName guards
// the proposal's "if user provides name:, that wins" contract by
// driving the full getStepDisplayName path.
func TestSynthesizeStepName_NamedStepWinsViaGetStepDisplayName(t *testing.T) {
	step := config.Step{
		Name:  "Install Foo",
		Shell: &config.ShellAction{Cmd: "echo hi"},
	}
	ec := &ExecutionContext{Scope: NewVariableScope()}
	got, ok := GetStepDisplayName(step, ec)
	if !ok || got != "Install Foo" {
		t.Errorf("named step must use user-supplied name; got %q (ok=%v)", got, ok)
	}
}

// TestSynthesizeStepName_UnnamedSurfacesSynthesizedViaGetStepDisplayName
// pins the integration: unnamed step → synthesizer → returned via
// the (name, true) tuple so renderers + event consumers see the
// label.
func TestSynthesizeStepName_UnnamedSurfacesSynthesizedViaGetStepDisplayName(t *testing.T) {
	step := config.Step{Shell: &config.ShellAction{Cmd: "echo hi"}}
	ec := &ExecutionContext{Scope: NewVariableScope()}
	got, ok := GetStepDisplayName(step, ec)
	if !ok {
		t.Fatalf("unnamed step must now have a synthesized display name")
	}
	if got != "shell: echo hi" {
		t.Errorf("synthesized name = %q, want %q", got, "shell: echo hi")
	}
}
