- name: Uninstall clair
  pkg:
    name: clair
    state: absent
  failed_when: false

- name: Display confirmation
  log: "clair uninstalled"
- name: Verify uninstallation with assert
  assert:
    command:
      cmd: command -v clair
      exit_code: 1
