package docgen

import (
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// TestDocsRegenGate_CoversCLISurface guards the CLI-doc half of the pre-commit
// gate. dist/docs/cli/*.md is generated by walking the live urfave/cli command
// tree (Generator.writeCLITree), whose flags/commands/help text are defined
// across the WHOLE cmd/ tree — not just the docs/schema commands. So a flag or
// command change anywhere under cmd/ can drift the committed CLI pages.
//
// The gate must therefore cover every Go file under cmd/. This test asserts
// exactly that, using git's own pathspec semantics for both sides so the check
// matches what the script actually does at commit time: it extracts the gate's
// pathspecs from scripts/docs-regen-staged.sh and confirms `git ls-files` over
// them is a superset of the full cmd/ tree. Narrowing the gate back to a
// hand-picked subset (the original 'cmd/docs.go'/'cmd/schema.go', which matched
// zero files) fails here.
func TestDocsRegenGate_CoversCLISurface(t *testing.T) {
	repoRoot := filepath.Join("..", "..")
	script := filepath.Join(repoRoot, "scripts", "docs-regen-staged.sh")

	raw, err := os.ReadFile(script)
	if err != nil {
		t.Fatalf("read %s: %v", script, err)
	}

	// Truth: every tracked Go file under cmd/. 'cmd/*.go' uses git's non-magic
	// '*' (matches '/'), so this is the entire cmd/ tree, top-level and nested.
	wantCovered := gitLsFiles(t, repoRoot, "cmd/*.go")
	if len(wantCovered) == 0 {
		t.Fatal("git ls-files found no cmd/*.go files — test wiring is wrong")
	}

	// What the gate actually covers: run git ls-files over the gate's own
	// pathspecs, so coverage is decided by real git semantics, not a substring.
	gateSpecs := extractGatePathspecs(string(raw))
	if len(gateSpecs) == 0 {
		t.Fatalf("found no gate pathspecs in %s — did the script format change?", script)
	}
	covered := make(map[string]bool)
	for _, f := range gitLsFiles(t, repoRoot, gateSpecs...) {
		covered[f] = true
	}

	var missing []string
	for _, f := range wantCovered {
		if !covered[f] {
			missing = append(missing, f)
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		t.Errorf("%d cmd/ Go file(s) define the CLI surface but are NOT gated by %s — "+
			"flag/command edits there will leave dist/docs/cli/*.md stale. Ensure 'cmd/*.go' "+
			"is in the gated pathspecs. Uncovered:\n  %s",
			len(missing), script, strings.Join(missing, "\n  "))
	}
}

// extractGatePathspecs pulls the active single-quoted pathspecs out of the
// script's `gated=$(git diff --cached … -- '<spec>' … 2>/dev/null …)` block.
//
// It scopes to that one command region first — crucial, because the comments
// above it contain illustrative quoted globs (e.g. '**/*.go', '<pkg>/*.go')
// that are NOT real gate inputs; pulling '**/*.go' from a comment would match
// nearly every file and make this guard pass vacuously. Within the region it
// keeps only quoted, whitespace-free '*.go' tokens — exactly what the gate
// diffs against.
func extractGatePathspecs(script string) []string {
	start := strings.Index(script, "git diff --cached")
	if start < 0 {
		return nil
	}
	region := script[start:]
	if end := strings.Index(region, "2>/dev/null"); end >= 0 {
		region = region[:end]
	}

	quoted := regexp.MustCompile(`'([^'\s]+\.go)'`)
	var specs []string
	for _, m := range quoted.FindAllStringSubmatch(region, -1) {
		specs = append(specs, m[1])
	}
	return specs
}

// gitLsFiles returns the tracked files matching the given pathspecs, run from
// repoRoot so pathspecs resolve against the repo as the gate script does.
func gitLsFiles(t *testing.T, repoRoot string, pathspecs ...string) []string {
	t.Helper()
	args := append([]string{"ls-files", "--"}, pathspecs...)
	cmd := exec.Command("git", args...)
	cmd.Dir = repoRoot
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("git ls-files %v: %v", pathspecs, err)
	}
	var files []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if line != "" {
			files = append(files, line)
		}
	}
	return files
}
