package docgen

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/urfave/cli/v2"

	_ "github.com/alehatsman/mooncake/internal/register" // populate the action registry
)

// TestGenerateDist_FileTreeShape asserts the dist tree has the expected
// top-level shape and that the file list returned matches what's on
// disk. The exact action / cli counts depend on the registry — we just
// verify the *categories* are present.
func TestGenerateDist_FileTreeShape(t *testing.T) {
	gen := NewGenerator("test")
	out := t.TempDir()

	written, err := gen.GenerateDist(DistOptions{
		OutDir:  out,
		CLIRoot: &cli.App{Name: "mooncake", Commands: []*cli.Command{{Name: "apply", Usage: "u"}}},
	})
	if err != nil {
		t.Fatalf("GenerateDist: %v", err)
	}

	if len(written) == 0 {
		t.Fatalf("expected at least some files written")
	}

	// Every returned path must exist on disk.
	for _, p := range written {
		if _, err := os.Stat(p); err != nil {
			t.Errorf("returned path missing on disk: %s (%v)", p, err)
		}
	}

	// Every returned path must be sorted (callers rely on stable order
	// for drift detection + index generation).
	if !sort.StringsAreSorted(written) {
		t.Error("written paths are not sorted")
	}

	// Required top-level pages.
	for _, rel := range []string{"index.md", "llms.txt", "SUMMARY.md", "schema.md", "properties.md"} {
		if _, err := os.Stat(filepath.Join(out, rel)); err != nil {
			t.Errorf("missing required page %s: %v", rel, err)
		}
	}

	// At least one action card (registry has many).
	actions, err := os.ReadDir(filepath.Join(out, "actions"))
	if err != nil || len(actions) == 0 {
		t.Errorf("expected actions/ to be populated, got %d entries (err=%v)", len(actions), err)
	}

	// CLI dir contains the synthetic command we passed in.
	if _, err := os.Stat(filepath.Join(out, "cli", "apply.md")); err != nil {
		t.Errorf("expected cli/apply.md from synthetic CLIRoot: %v", err)
	}
}

// TestGenerateDist_Deterministic asserts two consecutive regenerations
// into separate temp dirs produce byte-identical output. This is the
// load-bearing invariant for docs-check.sh — if it ever fails, the
// drift gate becomes flaky.
func TestGenerateDist_Deterministic(t *testing.T) {
	gen1 := NewGenerator("test")
	gen2 := NewGenerator("test")
	out1, out2 := t.TempDir(), t.TempDir()

	if _, err := gen1.GenerateDist(DistOptions{OutDir: out1}); err != nil {
		t.Fatalf("regen 1: %v", err)
	}
	if _, err := gen2.GenerateDist(DistOptions{OutDir: out2}); err != nil {
		t.Fatalf("regen 2: %v", err)
	}

	// Walk one tree and compare each file against its sibling.
	err := filepath.Walk(out1, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		rel, _ := filepath.Rel(out1, path)
		a, errA := os.ReadFile(path)                     // #nosec G304 -- test
		b, errB := os.ReadFile(filepath.Join(out2, rel)) // #nosec G304 -- test
		if errA != nil || errB != nil {
			t.Errorf("read %s: a=%v b=%v", rel, errA, errB)
			return nil
		}
		if string(a) != string(b) {
			t.Errorf("non-deterministic output: %s differs between regens", rel)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk: %v", err)
	}
}

// TestWriteActionCards_Skeleton asserts every emitted action card has
// the YAML front matter and the standard headings that agents and
// MkDocs rely on. Sampling one card is enough — the emitter is a loop,
// not a per-action switch.
func TestWriteActionCards_Skeleton(t *testing.T) {
	gen := NewGenerator("test")
	out := t.TempDir()

	written, err := gen.writeActionCards(out)
	if err != nil {
		t.Fatalf("writeActionCards: %v", err)
	}
	if len(written) == 0 {
		t.Fatal("no action cards written")
	}

	body, err := os.ReadFile(written[0]) // #nosec G304 -- test
	if err != nil {
		t.Fatalf("read sample card: %v", err)
	}
	s := string(body)

	for _, marker := range []string{
		"---\n",               // front matter open
		"type: action\n",      // type marker for agents
		"name: ",              // action name in front matter
		"capabilities:\n",     // capabilities sub-block
		"# ",                  // H1 title
		"## Platform Support", // required heading
		"<!-- Generated by mooncake docs generate; version test -->", // deterministic footer
	} {
		if !strings.Contains(s, marker) {
			t.Errorf("action card missing marker %q in %s", marker, written[0])
		}
	}

	// Footer must not contain a timestamp pattern (that's the bug we
	// shipped a fix for; regression test).
	if strings.Contains(s, "Generated: 20") || strings.Contains(s, "Generated: 19") {
		t.Errorf("action card contains a Generated: timestamp (determinism regression):\n%s", s)
	}
}

// TestWriteCLITree_SkipsHelpAndHidden asserts the CLI walker filters
// urfave/cli's auto-generated `help` subcommand and any `Hidden: true`
// nodes. Without these filters the rendered site doubles in page count
// and exposes commands that `mooncake --help` deliberately doesn't.
func TestWriteCLITree_SkipsHelpAndHidden(t *testing.T) {
	gen := NewGenerator("test")
	out := t.TempDir()

	app := &cli.App{
		Name: "mooncake",
		Commands: []*cli.Command{
			{Name: "apply", Usage: "u"},
			{Name: "help", Usage: "auto-injected by urfave/cli"},
			{Name: "secret", Usage: "hidden", Hidden: true},
			{Name: "outer", Subcommands: []*cli.Command{
				{Name: "inner", Usage: "u"},
				{Name: "h", Usage: "auto-help alias"},
			}},
		},
	}

	if _, err := gen.writeCLITree(out, app); err != nil {
		t.Fatalf("writeCLITree: %v", err)
	}

	got := map[string]bool{}
	entries, _ := os.ReadDir(filepath.Join(out, "cli"))
	for _, e := range entries {
		got[e.Name()] = true
	}

	want := []string{"apply.md", "outer.md", "outer_inner.md"}
	for _, w := range want {
		if !got[w] {
			t.Errorf("expected cli/%s, got entries: %v", w, got)
		}
	}
	for _, skip := range []string{"help.md", "secret.md", "outer_h.md"} {
		if got[skip] {
			t.Errorf("cli/%s should have been skipped", skip)
		}
	}
}

// TestWriteConceptCards_SkipsMissingReadme asserts the emitter doesn't
// crash or produce empty pages when a curated concept dir has no
// README.md — it just yields zero files for that dir.
func TestWriteConceptCards_SkipsMissingReadme(t *testing.T) {
	gen := NewGenerator("test")
	out := t.TempDir()

	// A dir we know has no README; emitter must tolerate that quietly.
	written, err := gen.writeConceptCards(out, []string{"definitely/not/a/real/path"})
	if err != nil {
		t.Fatalf("writeConceptCards: %v", err)
	}
	if len(written) != 0 {
		t.Errorf("expected 0 concept pages for missing dirs, got %d", len(written))
	}
}

// TestWriteConceptCards_RendersReadme asserts that when a README does
// exist, its body is rendered into a stable card skeleton (front matter
// + body + footer). Builds a fake package dir on disk so the test is
// self-contained.
func TestWriteConceptCards_RendersReadme(t *testing.T) {
	root := t.TempDir()
	pkg := filepath.Join(root, "fakepkg")
	if err := os.MkdirAll(pkg, 0o755); err != nil {
		t.Fatal(err)
	}
	readme := "# fakepkg\n\nThe fake package explains a thing.\n"
	if err := os.WriteFile(filepath.Join(pkg, "README.md"), []byte(readme), 0o644); err != nil {
		t.Fatal(err)
	}

	gen := NewGenerator("test")
	out := t.TempDir()
	written, err := gen.writeConceptCards(out, []string{pkg})
	if err != nil {
		t.Fatalf("writeConceptCards: %v", err)
	}
	if len(written) != 1 {
		t.Fatalf("expected 1 concept page, got %d", len(written))
	}

	body, _ := os.ReadFile(written[0]) // #nosec G304 -- test
	s := string(body)
	for _, marker := range []string{
		"type: concept",
		"name: fakepkg",
		"The fake package explains a thing.",
		"<!-- Generated by mooncake docs generate; version test -->",
	} {
		if !strings.Contains(s, marker) {
			t.Errorf("concept card missing %q", marker)
		}
	}
}

// TestWriteIndex_GroupsBySection asserts the index/llms.txt grouping
// puts files in their expected sections based on the top-level
// subdirectory in their relative path.
func TestWriteIndex_GroupsBySection(t *testing.T) {
	gen := NewGenerator("test")
	out := t.TempDir()

	// Synthesize a written-files list spanning known sections; the
	// emitter only reads the path strings, doesn't need the files to
	// exist on disk.
	if err := os.MkdirAll(filepath.Join(out, "actions"), 0o755); err != nil {
		t.Fatal(err)
	}
	written := []string{
		filepath.Join(out, "actions", "file_copy.md"),
		filepath.Join(out, "actions", "shell.md"),
		filepath.Join(out, "cli", "apply.md"),
		filepath.Join(out, "schema.md"),
	}

	paths, err := gen.writeIndex(out, written)
	if err != nil {
		t.Fatalf("writeIndex: %v", err)
	}
	if len(paths) != 2 {
		t.Fatalf("expected index.md + llms.txt (2 paths), got %d", len(paths))
	}

	llms, _ := os.ReadFile(filepath.Join(out, "llms.txt")) // #nosec G304 -- test
	s := string(llms)

	// Section headers must appear.
	for _, h := range []string{"## Actions", "## CLI", "## Reference"} {
		if !strings.Contains(s, h) {
			t.Errorf("llms.txt missing section header %q\n---\n%s", h, s)
		}
	}
	// Action entries use dotted names (not the on-disk _ form).
	if !strings.Contains(s, "[file.copy]") {
		t.Errorf("llms.txt should display file.copy with dot, not file_copy:\n%s", s)
	}
}

// TestWriteNav_SUMMARYFormat asserts SUMMARY.md is in the format
// mkdocs-literate-nav expects: top-level Home, then `- Section:`
// followed by indented `- [Title](path)` lines.
func TestWriteNav_SUMMARYFormat(t *testing.T) {
	gen := NewGenerator("test")
	out := t.TempDir()
	if err := os.MkdirAll(filepath.Join(out, "actions"), 0o755); err != nil {
		t.Fatal(err)
	}
	written := []string{
		filepath.Join(out, "actions", "shell.md"),
		filepath.Join(out, "schema.md"),
	}

	path, err := gen.writeNav(out, written)
	if err != nil {
		t.Fatalf("writeNav: %v", err)
	}
	body, _ := os.ReadFile(path) // #nosec G304 -- test
	s := string(body)

	if !strings.HasPrefix(s, "- [Home](index.md)\n") {
		t.Errorf("SUMMARY.md must start with Home entry; got: %q", s)
	}
	if !strings.Contains(s, "- Actions:\n    - [shell](actions/shell.md)") {
		t.Errorf("SUMMARY.md missing properly-indented Actions section:\n%s", s)
	}
}

// TestSplitReadme covers the small parser used by loadActionReadmes:
// front matter extraction, action: key lookup, H1 stripping, and the
// failure modes (no front matter, missing action key).
func TestSplitReadme(t *testing.T) {
	cases := []struct {
		name     string
		input    string
		wantName string
		wantBody string
	}{
		{
			name:     "full README with H1 and body",
			input:    "---\naction: file.copy\n---\n# file.copy\n\nProse here.\n",
			wantName: "file.copy",
			wantBody: "Prose here.\n",
		},
		{
			name:     "no front matter",
			input:    "# file.copy\n\nProse.\n",
			wantName: "",
			wantBody: "",
		},
		{
			name:     "front matter without action key",
			input:    "---\ntype: action\n---\n# file.copy\n",
			wantName: "",
			wantBody: "",
		},
		{
			name:     "body without H1",
			input:    "---\naction: shell\n---\nNo title here.\n",
			wantName: "shell",
			wantBody: "No title here.\n",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			name, body := splitReadme(c.input)
			if name != c.wantName {
				t.Errorf("name = %q, want %q", name, c.wantName)
			}
			if body != c.wantBody {
				t.Errorf("body = %q, want %q", body, c.wantBody)
			}
		})
	}
}

// TestLoadActionReadmes_SkipsStubs asserts the stub marker filters out
// boilerplate seed files. Builds a fake actions tree on disk so the
// test is hermetic.
func TestLoadActionReadmes_SkipsStubs(t *testing.T) {
	root := t.TempDir()

	mk := func(dir, body string) {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(root, dir, "README.md"), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	mk("copy",
		"---\naction: file.copy\n---\n"+stubMarker+"\n# file.copy\n\nstub prose\n")
	mk("shell",
		"---\naction: shell\n---\n# shell\n\nReal author-written prose.\n")
	mk("nameless",
		"---\ntype: action\n---\n# nameless\n\nbody\n") // no `action:` key → skipped

	notes, err := loadActionReadmes(root)
	if err != nil {
		t.Fatalf("loadActionReadmes: %v", err)
	}

	if _, ok := notes["file.copy"]; ok {
		t.Errorf("stub README for file.copy should have been skipped")
	}
	if got, ok := notes["shell"]; !ok {
		t.Errorf("authored README for shell missing")
	} else if !strings.Contains(got, "Real author-written prose") {
		t.Errorf("shell payload missing body content: %q", got)
	}
	if _, ok := notes["nameless"]; ok {
		t.Errorf("front-matter without action: should have been skipped")
	}
}

// TestLoadActionReadmes_MissingRootIsTolerated covers the production
// path where internal/actions doesn't exist (e.g. running docgen from
// a stripped binary). The function returns an empty map, no error.
func TestLoadActionReadmes_MissingRootIsTolerated(t *testing.T) {
	notes, err := loadActionReadmes("/definitely/not/a/real/path/internal/actions")
	if err != nil {
		t.Fatalf("expected nil error for missing root, got: %v", err)
	}
	if len(notes) != 0 {
		t.Errorf("expected empty map, got %d entries", len(notes))
	}
}
