package docgen

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/alehatsman/mooncake/internal/config"
	"gopkg.in/yaml.v3"
)

// generatePresetExamples generates documentation from actual preset files.
func (g *Generator) generatePresetExamples(w io.Writer, presetsDir string) error {
	// Generate metadata header
	write(w, "<!-- Generated by mooncake docs generate -->\n")
	write(w, "<!-- Version: %s | Generated: %s -->\n", g.Version, g.Timestamp.Format("2006-01-02 15:04:05 MST"))
	write(w, "<!-- Source: %s -->\n\n", presetsDir)

	// Find all preset files
	presetFiles, err := findPresetFiles(presetsDir)
	if err != nil {
		return fmt.Errorf("failed to find preset files: %w", err)
	}

	if len(presetFiles) == 0 {
		write(w, "*No preset files found in %s*\n", presetsDir)
		return nil
	}

	write(w, "## Preset Examples\n\n")
	write(w, "The following examples are generated from actual preset files in the repository.\n")
	write(w, "All syntax is validated and guaranteed to be correct.\n\n")

	// Process each preset file
	for i, presetFile := range presetFiles {
		if i > 0 {
			write(w, "\n---\n\n")
		}

		if err := g.generatePresetExample(w, presetFile); err != nil {
			write(w, "<!-- Error processing %s: %v -->\n\n", presetFile, err)
			continue
		}
	}

	return nil
}

// generatePresetExample generates documentation for a single preset file.
func (g *Generator) generatePresetExample(w io.Writer, presetPath string) error {
	// Read preset file
	data, err := os.ReadFile(presetPath) // #nosec G304 -- presetPath validated via findPresetFiles and PresetSearchPaths
	if err != nil {
		return fmt.Errorf("failed to read preset file: %w", err)
	}

	// Parse preset
	var preset config.PresetDefinition
	if err := yaml.Unmarshal(data, &preset); err != nil {
		return fmt.Errorf("failed to parse preset: %w", err)
	}

	// Generate documentation
	write(w, "### %s\n\n", preset.Name)

	if preset.Description != "" {
		write(w, "%s\n\n", preset.Description)
	}

	if preset.Version != "" {
		write(w, "**Version**: %s\n\n", preset.Version)
	}

	// Show file location
	relPath, _ := filepath.Rel(".", presetPath)
	write(w, "**Source**: `%s`\n\n", relPath)

	// Show parameters if any
	if len(preset.Parameters) > 0 {
		write(w, "**Parameters**:\n\n")

		// Sort parameters for consistent output
		paramNames := make([]string, 0, len(preset.Parameters))
		for name := range preset.Parameters {
			paramNames = append(paramNames, name)
		}
		sort.Strings(paramNames)

		for _, name := range paramNames {
			param := preset.Parameters[name]
			write(w, "- `%s` (%s)", name, param.Type)
			if param.Required {
				write(w, " **required**")
			}
			if param.Default != nil {
				write(w, " - default: `%v`", param.Default)
			}
			if len(param.Enum) > 0 {
				write(w, " - values: %v", param.Enum)
			}
			if param.Description != "" {
				write(w, " - %s", param.Description)
			}
			write(w, "\n")
		}
		write(w, "\n")
	}

	// Show usage example
	write(w, "**Usage**:\n\n")
	write(w, "```yaml\n")
	write(w, "- name: Use %s preset\n", preset.Name)
	write(w, "  preset: %s\n", preset.Name)

	if len(preset.Parameters) > 0 {
		write(w, "  with:\n")
		// Show required parameters
		paramNames := make([]string, 0, len(preset.Parameters))
		for name := range preset.Parameters {
			paramNames = append(paramNames, name)
		}
		sort.Strings(paramNames)

		for _, name := range paramNames {
			param := preset.Parameters[name]
			if param.Required {
				write(w, "    %s: <value>  # %s\n", name, param.Description)
			}
		}
	}
	write(w, "```\n\n")

	// Show preset definition structure (the correct format!)
	write(w, "**Preset Definition Structure**:\n\n")
	write(w, "```yaml\n")
	write(w, "name: %s\n", preset.Name)
	if preset.Description != "" {
		write(w, "description: %s\n", preset.Description)
	}
	if preset.Version != "" {
		write(w, "version: %s\n", preset.Version)
	}
	if len(preset.Parameters) > 0 {
		write(w, "\nparameters:\n")
		paramNames := make([]string, 0, len(preset.Parameters))
		for name := range preset.Parameters {
			paramNames = append(paramNames, name)
		}
		sort.Strings(paramNames)

		for _, name := range paramNames {
			param := preset.Parameters[name]
			write(w, "  %s:\n", name)
			write(w, "    type: %s\n", param.Type)
			if param.Required {
				write(w, "    required: true\n")
			}
			if param.Default != nil {
				write(w, "    default: %v\n", param.Default)
			}
			if len(param.Enum) > 0 {
				write(w, "    enum: %v\n", param.Enum)
			}
			if param.Description != "" {
				write(w, "    description: %s\n", param.Description)
			}
		}
	}
	write(w, "\nsteps:\n")
	write(w, "  # ... steps go here ...\n")
	write(w, "```\n")

	return nil
}

// findPresetFiles finds all preset.yml files in a directory tree.
func findPresetFiles(rootDir string) ([]string, error) {
	var presetFiles []string

	err := filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Skip directories
		if info.IsDir() {
			return nil
		}

		// Look for preset.yml files or standalone .yml files in presets root
		if info.Name() == "preset.yml" {
			presetFiles = append(presetFiles, path)
		} else if filepath.Dir(path) == rootDir && strings.HasSuffix(info.Name(), ".yml") {
			presetFiles = append(presetFiles, path)
		}

		return nil
	})

	if err != nil {
		return nil, err
	}

	// Sort for consistent output
	sort.Strings(presetFiles)

	return presetFiles, nil
}
