- name: Uninstall duf
  pkg:
    name: duf
    state: absent
  failed_when: false

- name: Display confirmation
  log: "duf uninstalled"
- name: Verify uninstallation with assert
  assert:
    command:
      cmd: command -v duf
      exit_code: 1
