- name: Uninstall lite-xl
  pkg:
    name: lite-xl
    state: absent
  failed_when: false

- name: Assert lite-xl is removed
  assert:
    command:
      cmd: command -v lite-xl
      exit_code: 1

- name: Display confirmation
  log: "lite-xl uninstalled"
