- name: Uninstall activemq
  pkg:
    name: activemq
    state: absent
  failed_when: false

- name: Verify uninstallation with assert
  assert:
    command:
      cmd: command -v activemq
      exit_code: 1

- name: Display confirmation
  log: "activemq uninstalled"
