#!/usr/bin/env bash
# Generate an architecture snapshot for LLM-assisted review.
#
# Produces a single markdown file summarising the package graph: per-package
# LOC and coupling (efferent/afferent/instability), the internal import edges,
# god-files, and — if the optional tools are installed — cyclomatic hotspots
# and goda's package summary.
#
# Usage:  scripts/arch-snapshot.sh [output-path]
# Default output: docs-working/ARCH_SNAPSHOT.md
set -euo pipefail

OUT="${1:-docs-working/ARCH_SNAPSHOT.md}"
mkdir -p "$(dirname "$OUT")"

MODULE=$(go list -m)
GO_VERSION=$(go version | awk '{print $3}')

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# One go-list pass: ImportPath \t Dir \t Imports(space-sep)
# Imports already exclude std lib? No — Imports includes everything. We filter to module-internal below.
go list -f '{{.ImportPath}}	{{.Dir}}	{{range .Imports}}{{.}} {{end}}' ./... > "$TMP/raw.tsv"

# Compute LOC per package (non-test .go files in pkg dir only, not recursive).
# Emit: pkg \t loc \t imports(internal, space-sep)
> "$TMP/pkgs.tsv"
while IFS=$'\t' read -r pkg dir imports; do
  loc=0
  if [ -d "$dir" ]; then
    loc=$(find "$dir" -maxdepth 1 -name '*.go' -not -name '*_test.go' -print0 2>/dev/null \
          | xargs -0 cat 2>/dev/null | wc -l | awk '{print $1}')
  fi
  internal_imports=""
  for imp in $imports; do
    case "$imp" in
      "$MODULE"|"$MODULE"/*) internal_imports="$internal_imports $imp" ;;
    esac
  done
  internal_imports="${internal_imports# }"
  printf '%s\t%s\t%s\n' "$pkg" "$loc" "$internal_imports" >> "$TMP/pkgs.tsv"
done < "$TMP/raw.tsv"

# Afferent (importer) counts: how many internal packages import each package.
awk -F'\t' '{
  n = split($3, arr, " ")
  for (i = 1; i <= n; i++) if (arr[i] != "") count[arr[i]]++
}
END { for (k in count) print k "\t" count[k] }' "$TMP/pkgs.tsv" > "$TMP/afferent.tsv"

# Build a lookup file: pkg \t loc \t efferent \t afferent \t instability(2dp)
awk -F'\t' '
NR == FNR { aff[$1] = $2; next }
{
  pkg = $1; loc = $2
  eff = 0
  n = split($3, arr, " ")
  for (i = 1; i <= n; i++) if (arr[i] != "") eff++
  a = (pkg in aff) ? aff[pkg] : 0
  total = eff + a
  inst = (total == 0) ? "n/a" : sprintf("%.2f", eff / total)
  printf "%s\t%s\t%s\t%s\t%s\n", pkg, loc, eff, a, inst
}' "$TMP/afferent.tsv" "$TMP/pkgs.tsv" > "$TMP/metrics.tsv"

{
  cat <<EOF
# Architecture Snapshot — \`$MODULE\`

Go: $GO_VERSION

This file is auto-generated by \`scripts/arch-snapshot.sh\`. Re-run after structural changes.

## How to read this

* **Efferent (out):** internal packages this one imports. High = depends on many things.
* **Afferent (in):** internal packages that import this one. High = many depend on it.
* **Instability:** efferent / (efferent + afferent). 0 = stable, 1 = unstable. Foundational packages should be near 0; leaves near 1. Mid-range with high LOC is often a smell.

## Packages (sorted by LOC)

| Package | LOC | Eff (out) | Aff (in) | Instab. |
|---|---:|---:|---:|---:|
EOF

  sort -t$'\t' -k2 -nr "$TMP/metrics.tsv" | while IFS=$'\t' read -r pkg loc eff aff inst; do
    short=${pkg#"$MODULE"/}
    [ "$short" = "$MODULE" ] && short="(root)"
    printf '| `%s` | %s | %s | %s | %s |\n' "$short" "$loc" "$eff" "$aff" "$inst"
  done

  cat <<'EOF'

## Internal import edges

```
EOF

  while IFS=$'\t' read -r pkg loc imports; do
    short_pkg=${pkg#"$MODULE"/}
    [ "$short_pkg" = "$MODULE" ] && short_pkg="(root)"
    for imp in $imports; do
      short_imp=${imp#"$MODULE"/}
      printf '%s -> %s\n' "$short_pkg" "$short_imp"
    done
  done < "$TMP/pkgs.tsv" | sort -u

  cat <<'EOF'
```

## God files (>500 LOC, non-test)

```
EOF

  find . -name '*.go' -not -name '*_test.go' \
       -not -path './vendor/*' -not -path './.git/*' -not -path './out/*' \
       -exec wc -l {} + 2>/dev/null \
    | awk '$1 > 500 && $2 != "total"' \
    | sort -nr \
    | head -30

  printf '```\n'

  if command -v gocyclo >/dev/null 2>&1; then
    cat <<'EOF'

## Cyclomatic hotspots (gocyclo > 15)

```
EOF
    # gocyclo exits non-zero when any function exceeds the threshold; mask that.
    { gocyclo -over 15 . 2>/dev/null || true; } | head -40
    printf '```\n'
  else
    cat <<'EOF'

## Cyclomatic hotspots

_gocyclo not installed — run `task install-tools`._
EOF
  fi

  if command -v goda >/dev/null 2>&1; then
    cat <<'EOF'

## goda cut — most "load-bearing" packages

Each row shows a package and what removing it would eliminate from the
indirect-dependency closure. High `Cut.PackageCount` = removing this package
prunes many transitive deps. Good targets for boundary-tightening.

Columns: `Package · InDegree · CutPackages · CutBytes · CutLOC`

```
EOF
    goda cut -exclude "std" "./..." > "$TMP/cut.txt" 2>/dev/null || true
    awk -v mod="$MODULE" 'NR==1 || $1 ~ "^"mod' "$TMP/cut.txt" | head -30 || true
    printf '```\n'
  else
    cat <<'EOF'

## goda summary

_goda not installed — run `task install-tools`._
EOF
  fi
} > "$OUT"

echo "Wrote $OUT"
wc -l "$OUT"
