- name: Check if procs is installed
  shell: command -v procs
  as: procs_check
  failed_when: false

- name: Install  via Homebrew
  pkg:
    name: procs
    state: present
  when: brew_available and procs_check.rc != 0

- name: Install procs via apt
  shell: cargo install procs
  when: linux and procs_check.rc != 0

- name: Verify installation with assert
  assert:
    command:
      cmd: command -v procs
      exit_code: 0

- name: Display confirmation
  log: "procs installed"
