- name: Uninstall entr
  pkg:
    name: entr
    state: absent
  failed_when: false

- name: Verify uninstallation with assert
  assert:
    command:
      cmd: command -v entr
      exit_code: 1

- name: Display confirmation
  log: "entr uninstalled"
